### ISSUE TITLE
Alpha transparent texture not found

### ISSUE THREAD

**Issue by pankti-fadia-inferenz** [echoARxyz/Unity-ARFoundation-echoAR-Face-Makeup#1]
where can I find Alpha transparent texture

**Comment by echo3Dco** [comment]
Thanks for reaching out @Pankti-Fadia!

Check out the open source project [Unity-ARFoundation-echo3D-example](https://github.com/echo3Dco/Unity-ARFoundation-echo3D-example) - it includes [code that allows to apply materials with alpha values in real-time](https://github.com/echo3Dco/Unity-ARFoundation-echo3D-example/search?q=alpha). For example, the [DefaultMaterialGenerator.cs](https://github.com/echo3Dco/Unity-ARFoundation-echo3D-example/blob/master/Assets/echo3D/Libraries/glTFast/Runtime/Scripts/DefaultMaterialGenerator.cs). 

Hope this helps!

**Comment by Chandan-kumar28** [comment]
how should i start contributing in echo3d @pankti-fadia-inferenz @bpedazur @echo3Dco
